-- 출력
-- 1. 회원목록을 출력한다 행번호 아이디 이름 연락처 성별
SELECT ROWNUM,USERID,NAME,MOBILE,GENDER FROM PENSION3;
SELECT * FROM PENSION3;
SELECT ROWNUM,PENSION3.* FROM PENSION3;
SELECT ROWNUM,P3.* FROM PENSION3 P3;

-- 2. 펜션목록을 출력한다 행번호 방번호 가격
SELECT ROWNUM,ROOM,PRICE FROM PENSION1;

-- 3. 제일 넓은방 정보를 출력한다 방번호 크기 가격
SELECT ROOM,RSIZE,PRICE FROM PENSION1 WHERE RSIZE = (SELECT MAX(RSIZE) FROM PENSION1);
-- 3-1 제일 작은방 정보를 출력한다 방번호 크기 가격
SELECT ROOM,RSIZE,PRICE FROM PENSION1 WHERE RSIZE = (SELECT MIN(RSIZE) FROM PENSION1);

-- 4. 예약 목록을 출력한다 방번호 체크인 체크아웃 예약자 * 날짜는 년-월-일
SELECT P2.ROOM 방번호,
TO_CHAR(P2.SDATE,'YYYY-MM-DD') 체크인,
TO_CHAR(P2.EDATE,'YYYY-MM-DD') 체크아웃,
P3.NAME 예약자
FROM PENSION2 P2, PENSION3 P3
WHERE P2.USERID=P3.USERID;

SELECT ROOM 방번호,
TO_CHAR(SDATE,'YYYY-MM-DD') 체크인,
TO_CHAR(EDATE,'YYYY-MM-DD') 체크아웃,
USERID 예약자
FROM PENSION2;

-- 5. 회원정보 출력 아이디 이름 성별 * 성별은 남성/여성으로 출력한다.
SELECT USERID,NAME,DECODE(GENDER,'M','남성','F','여성') GENDER FROM PENSION3;
SELECT P3.USERID,P3.NAME,P3.GENDER,P4.CD2 FROM PENSION3 P3,PENSION4 P4 WHERE P3.GENDER = P4.CD1;

-- 6. 예약 목록을 다음과 같이 출력한다. * 방번호 체크인 체크아웃 예약자 아이디 예약자명 연락처
SELECT P2.ROOM 방번호,
TO_CHAR(P2.SDATE,'YYYY-MM-DD') 체크인,
TO_CHAR(P2.EDATE,'YYYY-MM-DD') 체크아웃,
P3.NAME 예약자,
p2.USERID 아이디,
P3.NAME 예약자명,
P3.MOBILE 연락처
FROM PENSION2 P2, PENSION3 P3
WHERE P2.USERID=P3.USERID(+);

-- 7.오늘을 기점으로 기간이 지난 데이터를 출력한다. -> 순번 방번호 기간 아이디
-- 기간 : 0000/00/00 ~ 0000/00/00
SELECT ROWNUM 순번,
ROOM 방번호,
TO_CHAR(SDATE,'YYYY/MM/DD')||' ~ '||TO_CHAR(EDATE,'YYYY/MM/DD') 기간,
USERID 아이디
FROM PENSION2
WHERE EDATE < TO_CHAR(SYSDATE,'YYYY-MM-DD');

-- 8.오늘을 기점으로 예약된 데이터를 출력한다. -> 순번 방번호 기간 아이디 이름 연락처
-- 기간 : 0000/00/00 ~ 0000/00/00
SELECT ROWNUM 순번,
P2.ROOM 방번호,
TO_CHAR(P2.SDATE,'YYYY/MM/DD')||' ~ '||TO_CHAR(P2.EDATE,'YYYY/MM/DD') 기간,
P2.USERID 아이디,
P3.NAME 이름,
P3.MOBILE 연락처
FROM PENSION2 P2, PENSION3 P3
WHERE P2.USERID=P3.USERID AND P2.SDATE >= TO_CHAR(SYSDATE,'YYYY-MM-DD');

-- 9.아이디 test3의 예약사항을 출력한다 -> 순번 방번호 기간 아이디 이름 성별 상태
-- 완료 또는 예약 / 완료 : EDATE가 오늘날짜보다 작다 / 예약 : SDATE 가 오늘날짜 포함
-- 남성 또는 여성
SELECT ROWNUM 순번,
P2.ROOM 방번호,
TO_CHAR(P2.SDATE,'YYYY/MM/DD')||' ~ '||TO_CHAR(P2.EDATE,'YYYY/MM/DD') 기간,
P2.USERID 아이디,
P3.NAME 이름,
P4.CD2 성별,
?????????? 상태
FROM PENSION2 P2, PENSION3 P3, PENSION4 P4
WHERE P2.USERID='TEST3' AND P2.USERID=P3.USERID AND P3.GENDER = P4.CD1;

-- 초기
SELECT ROWNUM 순번,
P2.ROOM 방번호,
TO_CHAR(P2.SDATE,'YYYY/MM/DD')||' ~ '||TO_CHAR(P2.EDATE,'YYYY/MM/DD') 기간,
P2.USERID 아이디,
P3.NAME 이름,
DECODE(P3.GENDER,'M','남성','F','여성') GENDER,
(SELECT '완료' FROM DUAL WHERE P2.EDATE<SYSDATE)||
(SELECT '예약' FROM DUAL WHERE P2.EDATE>=SYSDATE) 상태
FROM PENSION2 P2, PENSION3 P3
WHERE P2.USERID='TEST3' AND P2.USERID=P3.USERID;

-- 완성
SELECT ROWNUM 순번,
P2.ROOM 방번호,
TO_CHAR(P2.SDATE,'YYYY/MM/DD')||' ~ '||TO_CHAR(P2.EDATE,'YYYY/MM/DD') 기간,
P2.USERID 아이디,
P3.NAME 이름,
DECODE(P3.GENDER,'M','남성','F','여성') GENDER,
NVL((SELECT '완료' FROM DUAL WHERE P2.EDATE<SYSDATE),'예정') 상태
FROM PENSION2 P2, PENSION3 P3
WHERE P2.USERID='TEST3' AND P2.USERID=P3.USERID;

-- 10.펜션 방번호 101의 이용내역을 출력한다. -> 순번 방번호 기간 아이디 상태
SELECT ROWNUM 순번,
P2.ROOM 방번호,
TO_CHAR(P2.SDATE,'YYYY/MM/DD')||' ~ '||TO_CHAR(P2.EDATE,'YYYY/MM/DD') 기간,
P2.USERID 아이디,
NVL((SELECT '완료' FROM DUAL WHERE P2.EDATE<SYSDATE),'예정') 상태
FROM PENSION2 P2
WHERE ROOM='101';

-- 11.2024년 10월의 매출액 출력하기 -> 년 월 매출액
SELECT P2.CODE,
P2.ROOM,
P1.PRICE
FROM PENSION2 P2, PENSION1 P1
WHERE P1.ROOM=P2.ROOM;

SELECT SUM(P1.PRICE) "매출액"
FROM PENSION2 P2, PENSION1 P1
WHERE P1.ROOM=P2.ROOM AND TO_CHAR(P2.EDATE,'YYYY-MM')='2024-10';
-- 날짜차이 :: 세로정렬일때 -(마이너스)가 무조건 아래 있어야함
SELECT TO_DATE('2024/10/15','YYYY/MM/DD') - TO_DATE('2024/10/14','YYYY/MM/DD') AS "날짜차이" FROM DUAL;

SELECT P2.CODE "코드",
P2.ROOM "방번호",
P1.PRICE "가격",
(P2.EDATE-P2.SDATE)"숙박일",
(P1.PRICE*(P2.EDATE-P2.SDATE)) "이용요금"
FROM PENSION2 P2, PENSION1 P1
WHERE P1.ROOM=P2.ROOM;

--정답
SELECT '2024-10' AS "날짜",
SUM(P1.PRICE*(P2.EDATE-P2.SDATE)) "매출액1",
TO_CHAR(SUM(P1.PRICE*(P2.EDATE-P2.SDATE)),'FM999,999,999') "매출액2"
FROM PENSION2 P2, PENSION1 P1
WHERE P1.ROOM=P2.ROOM
AND TO_CHAR(P2.SDATE,'YYYY-MM')='2024-10';

-- 번외
SELECT TO_CHAR('123456','999,999') FROM DUAL;