SELECT EMPNO,
ENAME,
(SELECT DEPT.DNAME FROM DEPT WHERE DEPT.DEPTNO=EMP.DEPTNO) DNAME
FROM EMP;

SELECT E.EMPNO,
E.ENAME,
D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO;

SELECT E.EMPNO EMPNO,
E.ENAME ENAME,
E.SAL SAL,
S.GRADE LEVEL1
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT E.EMPNO,
E.ENAME,
E.DEPTNO,
D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO(+);

SELECT E1.EMPNO EMPNO,
E1.ENAME ENAME,
E1.MGR MGR,
E2.ENAME MGRNAME
FROM EMP E1,EMP E2
WHERE E1.MGR=E2.EMPNO;

INSERT INTO DEPT VALUES('50','개발부','서울');

COMMIT;

SELECT E.EMPNO,E.ENAME,E.DEPTNO,D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO;

SELECT E.EMPNO,E.ENAME,E.DEPTNO,D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO(+);

-- (+) 위치를 반대로 두기
SELECT E.EMPNO,E.ENAME,E.DEPTNO,D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO(+)=D.DEPTNO;

