-- 1. 펜션 정보 테이블
CREATE TABLE PENSION1(
ROOM NUMBER(3) NOT NULL PRIMARY KEY,
RSIZE NUMBER(3) NOT NULL,
PRICE NUMBER DEFAULT '0'
);

-- 2. 예약정보 테이블
CREATE TABLE PENSION2(
CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
ROOM NUMBER(3) NOT NULL,
SDATE DATE,
EDATE DATE,
USERID VARCHAR2(50) NOT NULL
);
-- 1번 ROOM 2번 ROOM 을 외래키 설정
ALTER TABLE PENSION2 ADD CONSTRAINT PENSION2_FN FOREIGN KEY(ROOM) REFERENCES PENSION1(ROOM);

-- 시퀸스 설정
CREATE SEQUENCE PENSION2_SEQ
START WITH 1001
INCREMENT BY 1
MAXVALUE 999999;


-- 3. 회원번호 테이블
CREATE TABLE PENSION3(
USERID VARCHAR2(50) NOT NULL PRIMARY KEY,
PASS VARCHAR2(100) NOT NULL,
NAME VARCHAR2(50),
MOBILE VARCHAR2(50) NOT NULL,
GENDER CHAR(1) CHECK(GENDER IN('M','F'))
);

-- 4. 코드정보 테이블
CREATE TABLE PENSION4(
UNQ NUMBER NOT NULL PRIMARY KEY,
CD1 VARCHAR2(20) NOT NULL,
CD2 VARCHAR2(20) NOT NULL
);

CREATE SEQUENCE PENSION4_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999;

-- DROP TABLE PENSION4;