SELECT STD1.USERID,
STD1.NAME,
STD1.ADDR,
STD2.ENG,
STD2.KOR FROM STD1, STD2
WHERE STD1.USERID=STD2.USERID AND STD2.GUBUN='1';

SELECT STD1.USERID,
STD1.NAME,
STD2.ENG,
STD2.KOR,
(STD2.ENG+STD2.KOR) HAP,
ROUND((STD2.ENG+STD2.KOR)/3,2) AVG
FROM STD1,STD2
WHERE STD1.USERID=STD2.USERID
AND GUBUN='1';

SELECT S1.USERID,
S1.NAME,
S1.ADDR,
S2.ENG,
S2.KOR
FROM STD1 S1, STD2 S2
WHERE S1.USERID=S2.USERID
AND S2.GUBUN='1';