SELECT NVL('완료','예정') FROM DUAL WHERE '2024-10-14'<SYSDATE;

SELECT '완료' FROM DUAL WHERE 1=1; -- 완료 출력
SELECT '완료' FROM DUAL; -- 완료 출력

SELECT '완료' FROM DUAL WHERE 1=2; -- 출력 안됨
SELECT NVL('완료','예정') FROM DUAL WHERE 1=2; -- 출력 안됨

SELECT MAX('완료') FROM DUAL WHERE 1=2; -- NULL 출력
SELECT NVL(MAX('완료'),'예정') FROM DUAL WHERE 1=2; -- NVL 사용 :; 예정 출력

SELECT '완료' FROM DUAL WHERE 1=1; -- 완료 출력
SELECT '완료' FROM DUAL WHERE '2024-10-14'<SYSDATE; -- 완료 출력

SELECT '완료' FROM DUAL WHERE 1=2; -- 출력 안됨
SELECT '완료' FROM DUAL WHERE '2024-10-17'<SYSDATE; -- 출력 안됨

SELECT NVL('완료','예정') FROM DUAL WHERE 1=2; -- 출력 안됨
SELECT NVL('완료','예정') FROM DUAL WHERE '2024-10-17'<SYSDATE; -- 출력 안됨

SELECT
(SELECT NVL('완료','예정') FROM DUAL WHERE '2024-10-17'<SYSDATE) "상태"
FROM DUAL; -- NULL 출력

SELECT
NVL((SELECT '완료' FROM DUAL WHERE '2024-10-14'<SYSDATE),'예정') "상태"
FROM DUAL; -- NULL 출력
