--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-24-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD2SUB
--------------------------------------------------------

  CREATE TABLE "C##JAVA"."BOARD2SUB" 
   (	"UNQ" NUMBER, 
	"CONTENT" VARCHAR2(100 BYTE), 
	"PASS" VARCHAR2(100 BYTE), 
	"RDATE" TIMESTAMP (6), 
	"PUNQ" NUMBER, 
	"LEV" NUMBER(2,0) DEFAULT '3'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##JAVA.BOARD2SUB
SET DEFINE OFF;
Insert into C##JAVA.BOARD2SUB (UNQ,CONTENT,PASS,RDATE,PUNQ,LEV) values (98,'댓글 테스트 입니다.','1234',to_timestamp('24/12/24 16:54:06.000000000','RR/MM/DD HH24:MI:SSXFF'),56,5);
Insert into C##JAVA.BOARD2SUB (UNQ,CONTENT,PASS,RDATE,PUNQ,LEV) values (97,'댓글 테스트 입니다.','1234',to_timestamp('24/12/24 16:53:53.000000000','RR/MM/DD HH24:MI:SSXFF'),49,5);
--------------------------------------------------------
--  DDL for Index SYS_C007666
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##JAVA"."SYS_C007666" ON "C##JAVA"."BOARD2SUB" ("UNQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD2SUB
--------------------------------------------------------

  ALTER TABLE "C##JAVA"."BOARD2SUB" MODIFY ("UNQ" NOT NULL ENABLE);
  ALTER TABLE "C##JAVA"."BOARD2SUB" ADD PRIMARY KEY ("UNQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##JAVA"."BOARD2SUB" MODIFY ("LEV" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOARD2SUB
--------------------------------------------------------

  ALTER TABLE "C##JAVA"."BOARD2SUB" ADD FOREIGN KEY ("PUNQ")
	  REFERENCES "C##JAVA"."BOARD2" ("UNQ") ENABLE;
